# PyTorch3D rendering

mesh_dir: data/models
reference_texture_dir: data/textures/resized
texture_images_dir: data/textures/corrupted/images
texture_masks_dir: data/textures/corrupted/masks
render_dir: data/renders
reference_render_dir: data/renders/reference_rgb
reconstructed_dir: data/outputs/reconstructed_textures
final_renders_dir: data/outputs/final_renders
evaluation_dir: data/outputs/evaluation
outputs_dir: data/outputs

num_views: 4
image_size: 512

camera_distance: 2.0
elevation_range: [10, 60]
azimuth_range: [0, 360]