mesh_dir: data/models
reference_texture_dir: data/textures/resized
texture_images_dir: data/textures/corrupted/images
texture_masks_dir: data/textures/corrupted/masks
renders_dir: data/renders
reference_render_dir: data/renders/reference_rgb
outputs_dir: data/outputs
reconstructed_textures_dir: data/outputs/reconstructed_textures
final_renders_dir: data/outputs/final_renders
evaluation_dir: data/outputs/evaluation

image_size: 512

turntable_rings: 3
views_per_ring: 8

elev_mid: 0.0
elev_high: 45.0
elev_low: -45.0

add_top_bottom: true
elev_top: 85.0
elev_bottom: -85.0

camera_distance: 2.7

fov: 55.0