# PyTorch3D rendering

mesh_dir: data/models
reference_texture_dir: data/textures/resized
texture_images_dir: data/textures/corrupted/images
texture_masks_dir: data/textures/corrupted/masks
render_dir: data/renders
reference_render_dir: data/renders/reference_rgb
reconstructed_dir: data/outputs/reconstructed_textures
final_renders_dir: data/outputs/final_renders
evaluation_dir: data/outputs/evaluation
outputs_dir: data/outputs

num_views: 12
image_size: 512

camera_distance: 2.7 # 2.5 - 3.0

elevation_range: [10, 60]
azimuth_range: [0, 360]

fov: 60.0 # 45.0 - 75.0, field of view for rendering cameras, higher = wider angle and more distortion, lower = narrower angle and less distortion