# texture preprocessing

mesh_dir: data/models
input_dir: data/textures/original
resized_dir: data/textures/resized
corrupted_dir: data/textures/corrupted
inpainted_dir : data/outputs/inpainted_views
render_dir: data/renders

size: 512

extensions:
  - jpg
  - jpeg
  - png

quality: 95

corruption:
  num_shapes: 6
  line_thickness_min: 10
  line_thickness_max: 40