mesh_dir: data/models
textures_original_dir: data/textures/original
textures_resized_dir: data/textures/resized
textures_corrupted_dir: data/textures/corrupted
renders_dir: data/renders
inpainted_views_dir : data/outputs/inpainted_views

extensions: [jpg, jpeg, png]

resize:
  size: 512
  quality: 95

corruption:
  num_shapes: 3
  line_thickness_min: 4
  line_thickness_max: 15